version: "3.8"

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
volumes:
  postgres:
