name: Deploy Preview

on:
  push:
    branches-ignore:
      - master

jobs:
  vercel-deploy:
    name: Deploys Vercel to Preview
    runs-on: ubuntu-latest
    environment:
      name: Preview
      url: ${{ steps.deploy.outputs.preview-url }}

    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: deploy
        id: deploy
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-project-name: cclr6
          scope: cclr6
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}